/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.test.junit5;

import model.User;
import org.apache.http.HttpStatus;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.containsString;
import static org.hamcrest.MatcherAssert.assertThat;


class AppTest extends BaseTest{

    private static final String LIST_USERS_ENDPOINT = "/users";
    private static final String CREATE_USER_ENDPOINT = "/user";
    private static final String SHOW_USER_ENDPOINT = "/users/{userId}";

    @Test
    @Tag("contract")
    @DisplayName("Teste inicial")
    public void testShowSpecificUser() {
        User user = given().log().all().
                pathParam("userId", 2).
                when().
                get(SHOW_USER_ENDPOINT).
                then().log().all().
                statusCode(HttpStatus.SC_OK).
                extract().
                body().jsonPath().getObject("data", User.class);


        assertThat(user.getEmail(), containsString("@reqres.in"));
        assertThat(user.getName(), containsString("Janet"));
        assertThat(user.getLastName(), containsString("Weaver"));
    }
}
